version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 336369920320.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecs-test .
      - docker tag ecs-test:latest 336369920320.dkr.ecr.us-east-1.amazonaws.com/ecs-test:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 336369920320.dkr.ecr.us-east-1.amazonaws.com/ecs-test:latest
      - printf '[{"name":"ecs-test","imageUri":"%s"}]' 336369920320.dkr.ecr.us-east-1.amazonaws.com/ecs-test:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
